version: "3.10"
services:
  worker:
    build: .
    environment:
      AUTO_LEAVING_ASSISTANT: $AUTO_LEAVING_ASSISTANT # true
      BOT_TOKEN: 7340381347:AAFfVgtVNSyFCX-XNJav0gDGbRdXUODDRXA # true
      MONGO_DB_URI: mongodb+srv://TEAMBABY01:UTTAMRATHORE09@cluster0.vmjl9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 # true
      API_ID: 19769686  # true
      API_HASH: 515b64f5d2d955cdd6aa85a808fd4cb4  # true
      MUSIC_BOT_NAME: XezerMusicRobot  # true
      OWNER_ID: 7218327869  # true
      HEROKU_API_KEY: HRKU-d7849f0d-bd49-417a-9a6f-1453c10ad58a #default to none
      HEROKU_APP_NAME: XezerMusicRobot  # defaults to None
      LOG_GROUP_ID: -1002620193757  # true
      SUPPORT_GROUP: Xezer_Destek  # false
      SUPPORT_CHANNEL: Xezer_Botlar  # false
      START_IMG_URL: blob:https://web.telegram.org/812b54ad-35b1-466f-90ab-62970bfd6d53  # true
      UPSTREAM_REPO: $UPSTREAM_REPO  # true
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH  # true
      STRING_SESSION: $STRING_SESSION # true
      STRING_SESSION2: $STRING_SESSION2 # true
      SUDO_USERS: $SUDO_USERS #false
      BOT_ID: 7340381347 # true
